import { useState, useEffect, useId } from 'react';
import { useTheme } from '../../hooks/useTheme';

const mermaidPromise = import('mermaid').then((m) => m.default);

interface MermaidDiagramProps {
  code: string;
}

export function MermaidDiagram({ code }: MermaidDiagramProps) {
  const { isDark } = useTheme();
  const rawId = useId();
  const id = 'mermaid-' + rawId.replace(/:/g, '');
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const mermaid = await mermaidPromise;
        mermaid.initialize({
          startOnLoad: false,
          theme: isDark ? 'dark' : 'default',
          fontFamily: 'inherit',
        });

        const container = document.createElement('div');
        container.style.position = 'absolute';
        container.style.left = '-9999px';
        document.body.appendChild(container);

        try {
          const { svg: rendered } = await mermaid.render(id, code, container);
          if (!cancelled) {
            setSvg(rendered);
            setError(null);
          }
        } finally {
          container.remove();
        }
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : String(e));
          setSvg(null);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code, isDark, id]);

  if (error) {
    return (
      <div className="mb-4 rounded-lg overflow-hidden border border-red-300 dark:border-red-700">
        <div className="px-3 py-1.5 text-xs text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/30 border-b border-red-300 dark:border-red-700">
          Mermaid render error: {error}
        </div>
        <pre className="p-4 text-sm bg-slate-50 dark:bg-slate-800 overflow-x-auto">
          <code>{code}</code>
        </pre>
      </div>
    );
  }

  if (!svg) {
    return (
      <div className="mb-4 flex items-center justify-center p-8 rounded-lg bg-slate-50 dark:bg-slate-800 text-slate-400 dark:text-slate-500">
        <svg className="animate-spin h-5 w-5 mr-2" viewBox="0 0 24 24" fill="none">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
        Rendering diagram...
      </div>
    );
  }

  // SVG is generated by mermaid's rendering engine from controlled markdown source
  return (
    <div
      className="mb-4 flex justify-center p-4 rounded-lg bg-slate-50 dark:bg-slate-800 overflow-x-auto [&_svg]:max-w-full"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
